name: base
channels:
  - defaults
dependencies:
  - python=3.13
  - conda==25.3.1
  - setuptools
  - pip
  - wheel
  - conda-anaconda-telemetry
  - conda-anaconda-tos[version='>=0.1.3']
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - anaconda-anon-usage
