
name: ostrinia
# target: "nb_ostrinia"
target: "incrementing_ostrinia"
window: 12
horizon: 14
stride: 1
splitting:
  val_len: 0.1
  test_len: 0.2
connectivity:
  method: distance
  threshold: 0.1
  include_self: False
  layout: edge_index

log_metrics: ["mae", "mae_at_3_days", "mae_at_6_days", "mae_at_14_days", "mre", "mse"]
add_covariates: true
smooth: true
sampling: 2